name: e_receipt
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0

dependencies:
  dotted_line: ^3.2.3
  flutter:
    sdk: flutter
  google_fonts: ^6.3.3
  heroicons: ^0.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
